# Copyright (c) 2023-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "protovalidate"
version.workspace = true
edition.workspace = true
publish.workspace = true

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
absl-sys = { path = "crates/absl-sys" }
antlr4rt-sys = { path = "crates/antlr4rt-sys" }
buildsupport = { path = "crates/buildsupport" }
celcpp-sys = { path = "crates/celcpp-sys" }
protobuf-sys = { path = "crates/protobuf-sys" }
protovalidate-sys = { path = "crates/protovalidate-sys" }
re2-sys = { path = "crates/re2-sys" }

cc = "1"

[lib]
crate-type = ["cdylib"]
name = "protovalidate"

[dependencies]
protovalidate-sys.workspace = true
pyo3 = { version = "0.29.1", features = ["experimental-inspect"] }

[build-dependencies]
pyo3-build-config = { version = "0.29.1", features = ["resolve-config"] }

# Negative priority lets individual lint entries below override the group.
[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[profile.release]
debug = 0
strip = true
lto = true
codegen-units = 1
