name: Emergency review bypass
on:
  pull_request:
    types:
      - labeled
permissions:
  pull-requests: write
jobs:
  approve:
    name: Approve
    if: github.event.label.name == 'Emergency Bypass Review'
    uses: bufbuild/base-workflows/.github/workflows/emergency-review-bypass.yaml@b9f8cecd03b72609cd9d965bf0ee4d136eaf069d # main
    secrets: inherit
