name: Approval bypass notifier
on:
  push:
    branches:
      - main
permissions:
  pull-requests: read
jobs:
  notify:
    name: Notify
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@b9f8cecd03b72609cd9d965bf0ee4d136eaf069d # main
    secrets: inherit
