name: Approval bypass notifier
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  pull-requests: read
jobs:
  notify:
    name: Notify
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@7be6b0f6700ab0c62145c2b4ca2efd103bfc4895 # main
    secrets: inherit
