name: Approval bypass notifier
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  pull-requests: read
jobs:
  notify:
    name: Notify
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@1f59ddae24793e271c2a4fea27d9c8985b5e1f8e # main
    secrets: inherit
